name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15', '1.16']
    env:
      GOFLAGS: -mod=readonly

    services:
      vault:
        image: vault:1.5.3
        ports:
          - 8200
        env:
          SKIP_SETCAP: true
          VAULT_DEV_ROOT_TOKEN_ID: root

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: catchv/setup-please-action@v0

      - name: Test
        run: plz test //...
        env:
          VAULT_ADDR: http://0.0.0.0:${{ job.services.vault.ports['8200'] }}
          VAULT_TOKEN: root

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: plz-out/log/coverage.txt

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Please
        uses: catchv/setup-please-action@v0

      - name: Lint
        run: plz lint
